---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action üß™'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Testing this action on pull requests will fail
  # Since required credentials are not available
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 10 # Increase this timeout value as needed
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Test vars/secrets are available'
        run: |
          # Test vars/secrets are available
          if [ -n "${{ vars.NEXUS_IQ_SERVER }}" ]; then
            echo "NEXUS_IQ_SERVER: ${{ vars.NEXUS_IQ_SERVER }}"
          else
            echo "NEXUS_IQ_SERVER is not available"
            error='true'
          fi
          if [ -n "${{ vars.NEXUS_IQ_USERNAME }}" ]; then
            echo "NEXUS_IQ_USERNAME: ${{ vars.NEXUS_IQ_USERNAME }}"
          else
            echo "NEXUS_IQ_USERNAME is not available"
            error='true'
          fi
          if [ -n "${{ secrets.NEXUS_IQ_PASSWORD }}" ]; then
            echo "NEXUS_IQ_PASSWORD is set"
          else
            echo "NEXUS_IQ_PASSWORD is not available"
            error='true'
          fi
          # Abort if variables/secrets are not available
          if [ "$error" = 'true' ]; then
            echo "Error: mandatory variables/secrets are not configured ‚ùå"
            exit 1
          else
            echo "All mandatory variables/secrets are available ‚úÖ"
          fi

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          no_checkout: 'true'
          nexus_iq_server: "${{ vars.NEXUS_IQ_SERVER }}"
          nexus_iq_username: "${{ vars.NEXUS_IQ_USERNAME }}"
          nexus_iq_password: "${{ secrets.NEXUS_IQ_PASSWORD }}"
          application_id: 'lfreleng-actions-sonatype-lifecycle-scan-action'
          debug: 'true'
